export const headers = [
  "Product Name",
  "Color",
  "Size",
  "Category",
  "Price",
  "Stock",
  "Rating",
  "Discount",
  "Action",
];

export const data = [
  {
    productName: "Apple MacBook Pro 17",
    color: "Silver",
    size: "xl",
    category: "Laptop",
    price: "$2999",
    stock: "In Stock",
    rating: "4.5",
    discount: "10%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Samsung Galaxy S21",
    color: "Black",
    size: "6.2 inch",
    category: "Mobile Phone",
    price: "$899",
    stock: "Out of Stock",
    rating: "4.8",
    discount: "15%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Sony Bravia 4K TV",
    color: "Black",
    size: "55 inch",
    category: "Television",
    price: "$1299",
    stock: "In Stock",
    rating: "4.7",
    discount: "20%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Nike Air Max 90",
    color: "White",
    size: "US 10",
    category: "Footwear",
    price: "$129",
    stock: "In Stock",
    rating: "4.6",
    discount: "25%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Canon EOS R5",
    color: "Black",
    size: "Mirrorless",
    category: "Camera",
    price: "$3899",
    stock: "Out of Stock",
    rating: "4.9",
    discount: "5%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Dell Ultrasharp 27 Monitor",
    color: "Black",
    size: "27 inch",
    category: "Monitor",
    price: "$399",
    stock: "In Stock",
    rating: "4.7",
    discount: "12%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Beats Solo3 Wireless",
    color: "Rose Gold",
    size: "One Size",
    category: "Headphones",
    price: "$199",
    stock: "In Stock",
    rating: "4.4",
    discount: "8%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Asus ROG Strix G15",
    color: "Black",
    size: "15.6 inch",
    category: "Gaming Laptop",
    price: "$1799",
    stock: "In Stock",
    rating: "4.8",
    discount: "18%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Samsung Galaxy Watch 4",
    color: "Silver",
    size: "42mm",
    category: "Smartwatch",
    price: "$299",
    stock: "In Stock",
    rating: "4.5",
    discount: "10%",
    action: <a href="#">Edit</a>,
  },
  {
    productName: "Logitech MX Master 3",
    color: "Graphite",
    size: "One Size",
    category: "Computer Accessories",
    price: "$99",
    stock: "In Stock",
    rating: "4.6",
    discount: "15%",
    action: <a href="#">Edit</a>,
  },
];
